# Generated by Django 5.0.3 on 2024-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('descrip', models.TextField(null=True)),
            ],
        ),
    ]
