# Generated by Django 5.0.3 on 2024-05-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Poduct',
        ),
    ]
