# Generated by Django 5.0.3 on 2024-05-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_rename_product_poduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
