# Generated by Django 5.0.6 on 2024-06-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_producttag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product_module.producttag', verbose_name='برچسب'),
        ),
    ]
