# Generated by Django 5.0.6 on 2024-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.IntegerField(null=True, verbose_name='تخفیف'),
        ),
    ]
