# Generated by Django 5.0.6 on 2024-06-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_product_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
