# Generated by Django 5.0.6 on 2024-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.IntegerField(default=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_descript',
            field=models.TextField(max_length=200, null=True, verbose_name='توضیحات مختصر'),
        ),
    ]
